{
    'name': 'Fixer',
    'version': '17.0.1.0.0',
    'depends': ['base', 'hr', 'contacts'],
    'data': [
        'security/ir.model.access.csv',
        'views/clients.xml',
        'views/jobtype.xml',
        'views/equipment.xml',
        'views/brand.xml',
        'views/equipment_model.xml',
        'views/equipment_card.xml',
        'views/order_type.xml',
        'views/workman.xml',
        'views/orders.xml',
        'views/menu.xml',
    ],
    'installable': True,
    'application': True,
}